[features]
seeds = false
skip-lint = false

[programs.localnet]
s_usd = "6BMtkbE3ZmUvrdXf2ZGw1XfSuRQgRQJHgmtqrXsAD2ry"

[programs.devnet]
s_usd = "6BMtkbE3ZmUvrdXf2ZGw1XfSuRQgRQJHgmtqrXsAD2ry"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/admin1/Desktop/solana/w1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
