[features]
seeds = false
skip-lint = false
[programs.localnet]
s_usd = "64kP5mUqZ7ZHu3qXzmGSKyF5eBpUocsGX3eYqgXtcqhr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/admin1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
